# Generated by Django 4.2.7 on 2025-09-11 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Полная синхронизация'), ('partial', 'Частичная синхронизация'), ('products', 'Только товары'), ('images', 'Только изображения')], max_length=20, verbose_name='Тип синхронизации')),
                ('status', models.CharField(choices=[('started', 'Запущена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='started', max_length=20, verbose_name='Статус')),
                ('total_products', models.IntegerField(default=0, verbose_name='Всего товаров')),
                ('processed_products', models.IntegerField(default=0, verbose_name='Обработано товаров')),
                ('created_products', models.IntegerField(default=0, verbose_name='Создано товаров')),
                ('updated_products', models.IntegerField(default=0, verbose_name='Обновлено товаров')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Количество ошибок')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('error_details', models.TextField(blank=True, verbose_name='Детали ошибок')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('source_file_path', models.CharField(blank=True, max_length=500, verbose_name='Путь к исходному файлу')),
                ('source_file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер исходного файла')),
                ('source_file_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения файла')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='sync1c_sync_status_078cae_idx'), models.Index(fields=['sync_type', 'started_at'], name='sync1c_sync_sync_ty_6435e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='Код товара')),
                ('error_type', models.CharField(max_length=100, verbose_name='Тип ошибки')),
                ('error_message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('stack_trace', models.TextField(blank=True, verbose_name='Стек ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время возникновения')),
                ('sync_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='sync1c.synclog', verbose_name='Лог синхронизации')),
            ],
            options={
                'verbose_name': 'Ошибка синхронизации',
                'verbose_name_plural': 'Ошибки синхронизации',
                'ordering': ['-created_at'],
            },
        ),
    ]
