# Generated by Django 4.2.7 on 2025-09-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Понятное название, например, 'Основная база ПП'", max_length=255, verbose_name='Название источника')),
                ('code', models.SlugField(help_text="Короткий уникальный код, например, 'pp' или 'opt'", unique=True, verbose_name='Код источника')),
                ('json_file_path', models.CharField(help_text="Относительный путь к файлу данных от папки 'goods_data'", max_length=500, verbose_name='Путь к JSON файлу')),
                ('media_dir_path', models.CharField(help_text="Относительный путь к папке с медиафайлами от 'goods_data'", max_length=500, verbose_name='Путь к папке с медиа')),
                ('default_price_type_name', models.CharField(blank=True, help_text="Например, 'Розница' или 'Опт'", max_length=100, verbose_name='Название вида цены по умолчанию')),
                ('default_warehouse_name', models.CharField(blank=True, help_text="Например, 'Склад (№1)'", max_length=100, verbose_name='Название склада по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Источник данных 1С',
                'verbose_name_plural': 'Источники данных 1С',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('full', 'Полная'), ('partial', 'Частичная')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='synclog',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync1c.integrationsource', verbose_name='Источник данных'),
        ),
    ]
