# Generated by Django 4.2.7 on 2025-09-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0002_integrationsource_alter_synclog_sync_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsource',
            name='show_on_site',
            field=models.BooleanField(default=True, help_text='Если флаг установлен, товары из этого источника будут видны покупателям.', verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='integrationsource',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Источник будет использоваться для импорта только если он активен.', verbose_name='Активен'),
        ),
    ]
