# Generated by Django 4.2.7 on 2025-09-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0003_integrationsource_show_on_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsource',
            name='import_error_message',
            field=models.TextField(blank=True, help_text='Последнее сообщение об ошибке импорта', null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='import_status',
            field=models.CharField(choices=[('idle', 'Ожидание'), ('running', 'Выполняется'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='idle', help_text='Текущий статус импорта данных', max_length=20, verbose_name='Статус импорта'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='last_import_completed',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего успешного завершения импорта', null=True, verbose_name='Последнее завершение импорта'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='last_import_started',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего запуска импорта', null=True, verbose_name='Последний запуск импорта'),
        ),
    ]
