# Generated by Django 4.2.7 on 2025-09-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0004_integrationsource_import_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsource',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False, help_text='Включить автоматическую синхронизацию по расписанию', verbose_name='Автосинхронизация включена'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='data_sync_interval',
            field=models.PositiveIntegerField(default=5, help_text='Как часто синхронизировать данные (цены, остатки, названия) без медиафайлов', verbose_name='Интервал синхронизации данных (минуты)'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='full_sync_interval',
            field=models.PositiveIntegerField(default=60, help_text='Как часто выполнять полную синхронизацию включая медиафайлы', verbose_name='Интервал полной синхронизации (минуты)'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='last_data_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация данных'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='last_error_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последней ошибки'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='last_full_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя полная синхронизация'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='next_data_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая синхронизация данных'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='next_full_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая полная синхронизация'),
        ),
        migrations.AlterField(
            model_name='integrationsource',
            name='import_status',
            field=models.CharField(choices=[('idle', 'Ожидание'), ('running_data', 'Синхронизация данных'), ('running_full', 'Полная синхронизация'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='idle', help_text='Текущий статус импорта данных', max_length=20, verbose_name='Статус импорта'),
        ),
    ]
