# Generated by Django 4.2.7 on 2025-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0005_integrationsource_auto_sync_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsource',
            name='default_price_type',
            field=models.CharField(blank=True, help_text='UUID кода цены из 1С', max_length=255, null=True, verbose_name='Код вида цены по умолчанию'),
        ),
        migrations.AddField(
            model_name='integrationsource',
            name='default_warehouse',
            field=models.CharField(blank=True, help_text='UUID кода склада из 1С', max_length=255, null=True, verbose_name='Код склада по умолчанию'),
        ),
    ]
