# Generated by Django 4.2.7 on 2025-10-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0006_integrationsource_default_price_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsource',
            name='default_price_type_name',
        ),
        migrations.RemoveField(
            model_name='integrationsource',
            name='default_warehouse_name',
        ),
    ]
