# Generated by Django 4.2.7 on 2025-10-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название из 1С (автоматически обновляется при синхронизации)', max_length=255, verbose_name='Название категории')),
                ('display_name', models.CharField(blank=True, help_text='Альтернативное название для отображения на сайте. Если не заполнено, используется название из 1С', max_length=255, verbose_name='Название для показа')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL слаг')),
                ('code_category', models.CharField(blank=True, help_text='Уникальный код категории (например, из 1С) для синхронизации', max_length=100, verbose_name='Уникальный код категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение категории')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_visible_on_site', models.BooleanField(default=True, help_text='Если флаг снят, категория и все её товары не будут показаны на публичной части сайта', verbose_name='Показывать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='categories__parent__85acd9_idx'), models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'), models.Index(fields=['code_category'], name='categories__code_ca_e8a200_idx')],
            },
        ),
    ]
