# Generated by Django 4.2.7 on 2025-09-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_last_sync_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='last_sync_at',
        ),
        migrations.AddField(
            model_name='category',
            name='code_1c',
            field=models.CharField(blank=True, help_text='КодКатегории из 1С для синхронизации', max_length=100, verbose_name='Код категории из 1С'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code_1c'], name='categories__code_1c_fc0e09_idx'),
        ),
    ]
