# Generated by Django 4.2.7 on 2025-09-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_last_sync_at_category_code_1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_visible_on_site',
            field=models.BooleanField(default=True, help_text='Если флаг снят, категория и все её товары не будут показаны на публичной части сайта', verbose_name='Показывать на сайте'),
        ),
    ]
