# Generated by Django 4.2.7 on 2025-09-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_is_visible_on_site'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='categories__code_1c_fc0e09_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='code_1c',
        ),
        migrations.AddField(
            model_name='category',
            name='code_category',
            field=models.CharField(blank=True, help_text='Уникальный код категории (например, из 1С) для синхронизации', max_length=100, verbose_name='Уникальный код категории'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code_category'], name='categories__code_ca_e8a200_idx'),
        ),
    ]
