# Generated by Django 4.2.7 on 2025-10-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_category_categories__code_1c_fc0e09_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_name',
            field=models.CharField(blank=True, help_text='Альтернативное название для отображения на сайте. Если не заполнено, используется название из 1С', max_length=255, verbose_name='Название для показа'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Название из 1С (автоматически обновляется при синхронизации)', max_length=255, verbose_name='Название категории'),
        ),
    ]
