services:
  # База данных PostgreSQL
  db:
    image: postgres:15
    container_name: faida_db
    environment:
      POSTGRES_DB: faida_store
      POSTGRES_USER: faida_user
      POSTGRES_PASSWORD: faida_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - faida_network

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: faida_redis
    ports:
      - "6379:6379"
    networks:
      - faida_network

  # Django backend
  backend:
    build: ./backend
    container_name: faida_backend
    volumes:
      - ./backend:/app
      - ./data/goods:/app/goods_data  # Внешняя папка для данных 1С
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://faida_user:faida_password@db:5432/faida_store
      - REDIS_URL=redis://redis:6379/0
      - GOODS_DATA_PATH=/app/goods_data
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,backend,faida_backend,*
      - FRONTEND_URL=localhost:5173
    networks:
      - faida_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Планировщик синхронизации
  scheduler:
    build: ./backend
    container_name: faida_scheduler
    volumes:
      - ./backend:/app
      - ./data/goods:/app/goods_data
      - media_volume:/app/media
    depends_on:
      - db
      - redis
      - backend
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://faida_user:faida_password@db:5432/faida_store
      - REDIS_URL=redis://redis:6379/0
      - GOODS_DATA_PATH=/app/goods_data
    networks:
      - faida_network
    command: python manage.py run_scheduler
    restart: unless-stopped

  # Vite frontend (в режиме разработки)
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: faida_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - faida_network
    command: npm run dev

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  faida_network:
    driver: bridge