# Generated by Django 4.2.25 on 2025-10-11 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_notifications', models.BooleanField(default=True, verbose_name='Включить Email уведомления')),
                ('admin_email', models.EmailField(default='admin@faida.ru', max_length=254, verbose_name='Email администратора для уведомлений')),
                ('enable_whatsapp_notifications', models.BooleanField(default=False, verbose_name='Включить WhatsApp уведомления')),
                ('green_api_instance_id', models.CharField(blank=True, default='1103108965', max_length=20, verbose_name='Green API Instance ID')),
                ('green_api_token', models.CharField(blank=True, default='9a71dc1a5a274923967ab1cfe7dd56a976097823e41447eea1', max_length=100, verbose_name='Green API Token')),
                ('notify_on_new_order', models.BooleanField(default=True, verbose_name='Уведомлять о новых заказах')),
                ('notify_on_status_change', models.BooleanField(default=True, verbose_name='Уведомлять при смене статуса заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя оператора')),
                ('phone_number', models.CharField(help_text='Формат: +79285575774', max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'WhatsApp оператор',
                'verbose_name_plural': 'WhatsApp операторы',
                'ordering': ['name'],
            },
        ),
    ]
