# Generated by Django 4.2.25 on 2025-10-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'ordering': ['notification_type', 'channel', 'name'], 'verbose_name': 'Шаблон уведомления', 'verbose_name_plural': 'Шаблоны уведомлений'},
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Используется если для контакта не указан конкретный шаблон', verbose_name='Шаблон по умолчанию'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(default='Стандартный', help_text='Например: Стандартный, Подробный, Для VIP клиентов', max_length=200, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Кому отправлять уведомления', related_name='rules', to='notifications.notificationcontact', verbose_name='Контакты'),
        ),
        migrations.CreateModel(
            name='RuleContactTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationcontact', verbose_name='Контакт')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_templates', to='notifications.notificationrule', verbose_name='Правило')),
                ('template', models.ForeignKey(blank=True, help_text='Если не указан, используется шаблон по умолчанию для этого типа уведомления и канала', null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Назначение шаблона контакту',
                'verbose_name_plural': 'Назначения шаблонов контактам',
                'unique_together': {('rule', 'contact')},
            },
        ),
    ]
