# Generated by Django 4.2.25 on 2025-10-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='code',
            field=models.CharField(help_text='Тип канала (например: email, whatsapp, telegram)', max_length=50, verbose_name='Код канала'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='name',
            field=models.CharField(help_text='Уникальное название для идентификации канала', max_length=100, unique=True, verbose_name='Название канала'),
        ),
    ]
