# Generated by Django 4.2.25 on 2025-10-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationchannel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationcontact',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='notifications.notificationchannel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='notifications.notificationchannel', verbose_name='Канал'),
        ),
    ]
