# Generated by Django 4.2.25 on 2025-10-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_channel_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcontact',
            name='channel',
        ),
        migrations.AlterField(
            model_name='notificationcontact',
            name='channel_type',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='telegram', help_text='Тип канала для отправки уведомлений', max_length=50, verbose_name='Тип канала'),
        ),
    ]
