# Generated by Django 4.2.25 on 2025-10-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_add_unique_constraint_contact'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificationcontact',
            constraint=models.UniqueConstraint(fields=('channel_type', 'value'), name='unique_contact_per_channel_type'),
        ),
    ]
