# Generated by Django 4.2.25 on 2025-10-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_unique_constraint_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Системные шаблоны нельзя редактировать или удалять', verbose_name='Системный шаблон'),
        ),
    ]
