# Generated by Django 4.2.25 on 2025-10-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_change_template_to_channel_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('notification_type', 'channel_type', 'name'), name='unique_template_name_per_type_and_channel'),
        ),
    ]
