# Generated by Django 4.2.25 on 2025-10-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_move_variables_help_to_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='default_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон, используемый для всех контактов этого правила (если не указан индивидуальный)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_using_as_default', to='notifications.notificationtemplate', verbose_name='Шаблон по умолчанию'),
        ),
    ]
