# Generated by Django 4.2.25 on 2025-10-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notificationrule_default_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='name',
            field=models.CharField(default='Правило', help_text='Например: Отправка администратору, Уведомление менеджерам', max_length=200, verbose_name='Название правила'),
        ),
    ]
