# Generated by Django 4.2.25 on 2025-10-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_notificationrule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
    ]
