# Generated by Django 4.2.25 on 2025-10-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_alter_notificationlog_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='rule_type',
            field=models.CharField(choices=[('system', 'Системное'), ('additional', 'Дополнительное')], default='additional', help_text='Системное - отправка самому пользователю, Дополнительное - отправка контактам из списка', max_length=20, verbose_name='Тип правила'),
        ),
    ]
