# Generated by Django 4.2.25 on 2025-10-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_notificationrule_rule_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationrule',
            unique_together={('notification_type', 'channel', 'rule_type')},
        ),
    ]
