# Generated by Django 4.2.25 on 2025-10-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_alter_notificationrule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='default_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон, используемый для всех контактов этого правила (если не указан индивидуальный)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules_using_as_default', to='notifications.notificationtemplate', verbose_name='Шаблон по умолчанию'),
        ),
        migrations.AlterField(
            model_name='rulecontacttemplate',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Если не указан, используется шаблон по умолчанию для этого типа уведомления и канала', null=True, on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationtemplate', verbose_name='Шаблон'),
        ),
    ]
