# Generated by Django 4.2.25 on 2025-10-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_notificationrule_default_template_and_more'),
    ]

    operations = [
    ]
