# Generated by Django 4.2.25 on 2025-10-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_remove_is_default_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationtemplate',
            name='unique_default_template_per_type_and_channel',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='default_template',
            field=models.ForeignKey(help_text='Шаблон, используемый для всех контактов этого правила (если не указан индивидуальный)', on_delete=django.db.models.deletion.PROTECT, related_name='rules_using_as_default', to='notifications.notificationtemplate', verbose_name='Шаблон'),
        ),
    ]
