# Generated by Django 4.2.7 on 2025-10-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_deliveryaddress_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Долгота'),
        ),
    ]
