# Generated by Django 4.2.25 on 2025-10-10 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное поле. Не более 150 символов. Только латинские буквы, цифры и символы _-', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Имя пользователя может содержать только латинские буквы, цифры, символы подчеркивания (_) и дефисы (-).', regex='^[a-zA-Z0-9_-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
