# Generated by Django 4.2.7 on 2025-09-13 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock_for_display', models.PositiveIntegerField(default=1, help_text='Товары с остатком МЕНЬШЕ этого значения не будут показаны на сайте.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный остаток для показа')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
