# Generated by Django 4.2.7 on 2025-10-06 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock_for_display', models.PositiveIntegerField(default=1, help_text='Товары с остатком МЕНЬШЕ этого значения не будут показаны на сайте.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный остаток для показа')),
                ('default_stock_display_style', models.CharField(choices=[('exact', 'Показывать точное количество'), ('status', 'Показывать статус (В наличии / Нет)'), ('detailed_status', 'Показывать детальный статус (В наличии / Мало / Нет)')], default='detailed_status', help_text='Как показывать наличие товаров на сайте по умолчанию', max_length=20, verbose_name='Стиль отображения остатков по умолчанию')),
                ('default_low_stock_threshold', models.PositiveIntegerField(default=5, help_text="Количество, при котором товар будет считаться 'мало' по умолчанию", validators=[django.core.validators.MinValueValidator(1)], verbose_name="Порог 'Мало на складе' по умолчанию")),
                ('show_stock_quantities_globally', models.BooleanField(default=True, help_text='Если отключено, остатки не будут показываться пользователям', verbose_name='Показывать остатки на сайте')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
