# Generated by Django 4.2.7 on 2025-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Полный URL сайта для ссылок в уведомлениях (например: https://faida.ru). Если пусто, используется значение из переменной окружения FRONTEND_URL.',
                max_length=255,
                verbose_name='URL сайта'
            ),
        ),
    ]
