# Generated by Django 4.2.7 on 2025-09-14 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text="Количество, при котором товар будет считаться 'мало' по умолчанию", validators=[django.core.validators.MinValueValidator(1)], verbose_name="Порог 'Мало на складе' по умолчанию"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_stock_display_style',
            field=models.CharField(choices=[('exact', 'Показывать точное количество'), ('status', 'Показывать статус (В наличии / Нет)'), ('detailed_status', 'Показывать детальный статус (В наличии / Мало / Нет)')], default='detailed_status', help_text='Как показывать наличие товаров на сайте по умолчанию', max_length=20, verbose_name='Стиль отображения остатков по умолчанию'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_stock_quantities_globally',
            field=models.BooleanField(default=True, help_text='Если отключено, остатки не будут показываться пользователям', verbose_name='Показывать остатки на сайте'),
        ),
    ]
