# Generated by Django 4.2.27 on 2026-01-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Наличными при получении'), ('card_on_delivery', 'Картой при получении'), ('online', 'Оплата онлайн')], default='cash_on_delivery', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
