# Generated by Django 4.2.7 on 2025-10-08 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название должности')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL slug')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полное описание (HTML)')),
                ('employment_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('remote', 'Удаленная работа'), ('internship', 'Стажировка')], default='full_time', max_length=20, verbose_name='Тип занятости')),
                ('location', models.CharField(default='Махачкала', max_length=100, verbose_name='Город')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа')),
                ('file', models.FileField(blank=True, null=True, upload_to='jobs/%Y/%m/%d/', verbose_name='Файл')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL видео (YouTube/Vimeo)')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('display_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='jobs.job', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Медиа файл вакансии',
                'verbose_name_plural': 'Медиа файлы вакансий',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
