# Generated by Django 4.2.7 on 2025-10-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Изображение для отображения в списке вакансий', null=True, upload_to='jobs/previews/%Y/%m/%d/', verbose_name='Превью изображение для ленты'),
        ),
    ]
