# Generated by Django 4.2.7 on 2025-10-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Закрыта для откликов'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна на сайте'),
        ),
    ]
