# Generated by Django 4.2.7 on 2025-10-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_is_closed_alter_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_schedule',
            field=models.CharField(default='5/2 сб, вс выходной', max_length=255, verbose_name='График работы'),
        ),
    ]
