# Generated by Django 4.2.7 on 2025-10-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_work_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата от'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата до'),
        ),
    ]
