# Generated by Django 4.2.7 on 2025-10-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_salary_from_alter_job_salary_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hr_email',
            field=models.EmailField(default='hr@faida.ru', max_length=255, verbose_name='Email для откликов'),
        ),
        migrations.AddField(
            model_name='job',
            name='hr_phone',
            field=models.CharField(default='+7 (999) 123-45-67', max_length=20, verbose_name='Телефон для откликов'),
        ),
    ]
