# Generated by Django 4.2.7 on 2025-10-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_hr_email_job_hr_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hr_email',
            field=models.TextField(default='hr@faida.ru', help_text='Можно указать несколько email через запятую или с новой строки', verbose_name='Email для откликов'),
        ),
        migrations.AlterField(
            model_name='job',
            name='hr_phone',
            field=models.TextField(default='+7 (999) 123-45-67', help_text='Можно указать несколько телефонов через запятую или с новой строки', verbose_name='Телефон для откликов'),
        ),
    ]
