# Generated by Django 4.2.7 on 2025-10-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_hr_email_alter_job_hr_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content_delta',
            field=models.JSONField(blank=True, help_text='Quill Delta для сохранения форматирования', null=True, verbose_name='Quill Delta формат'),
        ),
    ]
