# Generated by Django 4.2.7 on 2025-10-09 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL слаг')),
                ('preview_image', models.ImageField(blank=True, help_text='Изображение для списка новостей', null=True, upload_to='news/previews/', verbose_name='Превью изображение')),
                ('short_description', models.TextField(help_text='Краткое описание для списка новостей', max_length=500, verbose_name='Краткое описание')),
                ('content', models.TextField(help_text='HTML контент новости', verbose_name='Полное содержание')),
                ('content_delta', models.JSONField(blank=True, help_text='Quill Delta для сохранения форматирования', null=True, verbose_name='Quill Delta формат')),
                ('is_published', models.BooleanField(default=True, help_text='Опубликована ли новость на сайте', verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, help_text='Дата и время публикации новости', null=True, verbose_name='Дата публикации')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Счетчик просмотров новости', verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL слаг')),
                ('display_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория новости',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа')),
                ('file', models.FileField(blank=True, help_text='Файл изображения или видео', null=True, upload_to='news/media/', verbose_name='Файл')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на видео (YouTube, Vimeo и т.д.)', max_length=500, null=True, verbose_name='URL видео')),
                ('caption', models.CharField(blank=True, help_text='Описание медиа-файла', max_length=255, verbose_name='Подпись')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Медиа-файл новости',
                'verbose_name_plural': 'Медиа-файлы новостей',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at'], name='news_news_publish_ad4867_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published'], name='news_news_is_publ_075179_idx'),
        ),
    ]
