# Generated by Django 4.2.27 on 2026-01-11 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(blank=True, help_text='Идентификатор магазина в YooKassa', max_length=50, verbose_name='Shop ID')),
                ('secret_key', models.CharField(blank=True, help_text='Секретный ключ для API YooKassa', max_length=100, verbose_name='Секретный ключ')),
                ('is_enabled', models.BooleanField(default=False, help_text='Если выключено, кнопка онлайн-оплаты будет скрыта', verbose_name='Включить онлайн-оплату')),
                ('test_mode', models.BooleanField(default=True, help_text='Использовать тестовое окружение YooKassa', verbose_name='Тестовый режим')),
                ('webhook_secret', models.CharField(blank=True, help_text='Опционально: для проверки подписи webhook запросов', max_length=100, verbose_name='Секрет для webhook')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Настройки платежей',
                'verbose_name_plural': 'Настройки платежей',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yookassa_id', models.CharField(max_length=50, unique=True, verbose_name='ID возврата в YooKassa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма возврата')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('succeeded', 'Выполнен'), ('canceled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('reason', models.TextField(blank=True, verbose_name='Причина возврата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'ordering': ['-created_at'],
            },
        ),
    ]
