# Generated by Django 4.2.7 on 2025-09-11 15:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код товара из 1С', max_length=50, unique=True, verbose_name='Код товара')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица измерения')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Вес')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('shelf_life', models.CharField(blank=True, max_length=100, verbose_name='Срок годности')),
                ('storage_conditions', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калории на 100г')),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Белки на 100г')),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Жиры на 100г')),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Углеводы на 100г')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('tags', models.TextField(blank=True, help_text='Теги через запятую', verbose_name='Теги')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_hash', models.CharField(blank=True, help_text='MD5 хэш данных из 1С для отслеживания изменений', max_length=64, verbose_name='Хэш для синхронизации')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='Категория')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Связанные товары')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'is_main'], name='products_pr_product_a6a200_idx'), models.Index(fields=['product', 'order'], name='products_pr_product_e55bb9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'is_active'], name='products_pr_in_stoc_1e7f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'in_stock'], name='products_pr_categor_17f124_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
    ]
