# Generated by Django 4.2.7 on 2025-10-06 22:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync1c', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код товара из 1С', max_length=50, unique=True, verbose_name='Код товара')),
                ('article', models.CharField(blank=True, help_text='Артикул товара из 1С', max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('barcodes', models.TextField(blank=True, help_text='Штрихкоды через запятую', verbose_name='Штрихкоды')),
                ('price', models.DecimalField(decimal_places=2, help_text='Основная цена для отображения (обычно цена для интернет-магазина)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('unit', models.CharField(default='шт', max_length=20, verbose_name='Единица измерения')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('stock_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Основное количество для отображения (обычно свободный остаток)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество на складе')),
                ('is_weighted', models.BooleanField(default=False, verbose_name='Весовой товар')),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес единицы товара')),
                ('prices_data', models.JSONField(blank=True, default=list, help_text='Массив с различными типами цен из 1С', verbose_name='Данные о ценах')),
                ('stocks_data', models.JSONField(blank=True, default=list, help_text='Массив с остатками по складам из 1С', verbose_name='Данные об остатках')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Вес')),
                ('composition', models.TextField(blank=True, verbose_name='Состав')),
                ('shelf_life', models.CharField(blank=True, max_length=100, verbose_name='Срок годности')),
                ('storage_conditions', models.TextField(blank=True, verbose_name='Условия хранения')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('tags', models.TextField(blank=True, help_text='Теги через запятую', verbose_name='Теги')),
                ('selected_price_code', models.CharField(blank=True, help_text='Код вида цены из 1С, который будет основным на сайте.', max_length=100, null=True, verbose_name='Код выбранной цены')),
                ('selected_stock_code', models.CharField(blank=True, help_text='Код склада из 1С, остатки которого будут основными на сайте.', max_length=100, null=True, verbose_name='Код выбранного склада')),
                ('use_default_stock_settings', models.BooleanField(default=True, help_text='Если включено, будут использоваться общие настройки сайта. Если выключено - индивидуальные настройки товара.', verbose_name='Использовать общие настройки остатков')),
                ('stock_display_style', models.CharField(choices=[('exact', 'Показывать точное количество'), ('status', 'Показывать статус (В наличии / Нет)'), ('detailed_status', 'Показывать детальный статус (В наличии / Мало / Нет)')], default='detailed_status', help_text='Как показывать наличие товара на сайте (действует только при отключенных общих настройках).', max_length=20, verbose_name='Стиль отображения остатков (индивидуальный)')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text="Количество, при котором товар будет считаться 'мало' (действует только при отключенных общих настройках).", verbose_name="Порог 'Мало на складе' (индивидуальный)")),
                ('is_visible_on_site', models.BooleanField(default=True, help_text='Если флаг снят, товар не будет показан на публичной части сайта', verbose_name='Активен на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_hash', models.CharField(blank=True, help_text='MD5 хэш данных из 1С для отслеживания изменений', max_length=64, verbose_name='Хэш для синхронизации')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category', verbose_name='Категория')),
                ('related_products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Связанные товары')),
                ('source', models.ForeignKey(blank=True, help_text='Указывает, из какой базы 1С пришел этот товар.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync1c.integrationsource', verbose_name='Источник данных 1С')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_hash', models.CharField(blank=True, help_text='MD5 хэш исходного файла для определения изменений', max_length=32, verbose_name='MD5 хэш файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['-is_main', 'order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'is_main'], name='products_pr_product_a6a200_idx'), models.Index(fields=['product', 'order'], name='products_pr_product_e55bb9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_pr_code_4c2607_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'is_visible_on_site'], name='products_pr_in_stoc_2f96e8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'in_stock'], name='products_pr_categor_17f124_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
    ]
