# Generated by Django 4.2.7 on 2025-09-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, help_text='Артикул товара из 1С', max_length=100, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcodes',
            field=models.TextField(blank=True, help_text='Штрихкоды через запятую', verbose_name='Штрихкоды'),
        ),
    ]
