# Generated by Django 4.2.25 on 2025-10-13 20:45

from django.db import migrations, models
import django.db.models.deletion


def migrate_brands_forward(apps, schema_editor):
    """Переносим данные из CharField brand в модель Brand."""
    Product = apps.get_model('products', 'Product')
    Brand = apps.get_model('products', 'Brand')

    # Получаем все уникальные бренды из существующих товаров
    unique_brands = Product.objects.exclude(brand_temp__isnull=True).exclude(brand_temp='').values_list('brand_temp', flat=True).distinct()

    # Создаем объекты Brand для каждого уникального бренда
    for brand_name in unique_brands:
        Brand.objects.get_or_create(name=brand_name)

    # Связываем товары с созданными брендами
    for product in Product.objects.all():
        if product.brand_temp:
            try:
                brand = Brand.objects.get(name=product.brand_temp)
                product.brand = brand
                product.save()
            except Brand.DoesNotExist:
                pass


def migrate_brands_backward(apps, schema_editor):
    """Обратная миграция - копируем имена брендов обратно в brand_temp."""
    Product = apps.get_model('products', 'Product')

    for product in Product.objects.select_related('brand').all():
        if product.brand:
            product.brand_temp = product.brand.name
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        # 1. Создаем модель Brand
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название бренда')),
                ('logo', models.ImageField(blank=True, help_text='Иконка бренда для отображения в карточке товара', null=True, upload_to='brands/', verbose_name='Логотип бренда')),
                ('description', models.TextField(blank=True, verbose_name='Описание бренда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),

        # 2. Переименовываем старое поле brand в brand_temp
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_temp',
        ),

        # 3. Добавляем новое поле brand как ForeignKey
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='Бренд'),
        ),

        # 4. Мигрируем данные
        migrations.RunPython(migrate_brands_forward, migrate_brands_backward),

        # 5. Удаляем временное поле brand_temp
        migrations.RemoveField(
            model_name='product',
            name='brand_temp',
        ),
    ]
