# Generated by Django 4.2.7 on 2025-09-11 21:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_article_product_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_weighted',
            field=models.BooleanField(default=False, verbose_name='Весовой товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='prices_data',
            field=models.JSONField(blank=True, default=list, help_text='Массив с различными типами цен из 1С', verbose_name='Данные о ценах'),
        ),
        migrations.AddField(
            model_name='product',
            name='stocks_data',
            field=models.JSONField(blank=True, default=list, help_text='Массив с остатками по складам из 1С', verbose_name='Данные об остатках'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес единицы товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Основная цена для отображения (обычно цена для интернет-магазина)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Основное количество для отображения (обычно свободный остаток)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Количество на складе'),
        ),
    ]
