# Generated by Django 4.2.7 on 2025-09-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_weighted_product_prices_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proteins',
        ),
    ]
