# Generated by Django 4.2.7 on 2025-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_calories_remove_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text="Количество, при котором товар будет считаться 'мало'.", verbose_name="Порог 'Мало на складе'"),
        ),
        migrations.AddField(
            model_name='product',
            name='selected_price_code',
            field=models.CharField(blank=True, help_text='Код вида цены из 1С, который будет основным на сайте.', max_length=100, null=True, verbose_name='Код выбранной цены'),
        ),
        migrations.AddField(
            model_name='product',
            name='selected_stock_code',
            field=models.CharField(blank=True, help_text='Код склада из 1С, остатки которого будут основными на сайте.', max_length=100, null=True, verbose_name='Код выбранного склада'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_display_style',
            field=models.CharField(choices=[('exact', 'Показывать точное количество'), ('status', 'Показывать статус (В наличии / Нет)'), ('detailed_status', 'Показывать детальный статус (В наличии / Мало / Нет)')], default='detailed_status', help_text='Как показывать наличие товара на сайте.', max_length=20, verbose_name='Стиль отображения остатков'),
        ),
    ]
