# Generated by Django 4.2.7 on 2025-09-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0002_integrationsource_alter_synclog_sync_type_and_more'),
        ('products', '0005_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Указывает, из какой базы 1С пришел этот товар.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sync1c.integrationsource', verbose_name='Источник данных 1С'),
        ),
    ]
