# Generated by Django 4.2.7 on 2025-09-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', help_text='Например, кг, шт, л', max_length=50, verbose_name='Единица измерения'),
        ),
    ]
