# Generated by Django 4.2.7 on 2025-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт', max_length=20, verbose_name='Единица измерения'),
        ),
    ]
