# Generated by Django 4.2.7 on 2025-09-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_visible_on_site',
            field=models.BooleanField(default=True, help_text='Если флаг снят, товар не будет показан на публичной части сайта', verbose_name='Показывать на сайте'),
        ),
    ]
