# Generated by Django 4.2.7 on 2025-09-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_visible_on_site'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_in_stoc_1e7f3f_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_visible_on_site',
            field=models.BooleanField(default=True, help_text='Если флаг снят, товар не будет показан на публичной части сайта', verbose_name='Активен на сайте'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'is_visible_on_site'], name='products_pr_in_stoc_2f96e8_idx'),
        ),
    ]
