# Generated by Django 4.2.7 on 2025-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='file_hash',
            field=models.CharField(blank=True, help_text='MD5 хэш исходного файла для определения изменений', max_length=32, verbose_name='MD5 хэш файла'),
        ),
    ]
