# Generated by Django 4.2.7 on 2025-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_add_file_hash_to_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='use_default_stock_settings',
            field=models.BooleanField(default=True, help_text='Если включено, будут использоваться общие настройки сайта. Если выключено - индивидуальные настройки товара.', verbose_name='Использовать общие настройки остатков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text="Количество, при котором товар будет считаться 'мало' (действует только при отключенных общих настройках).", verbose_name="Порог 'Мало на складе' (индивидуальный)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_display_style',
            field=models.CharField(choices=[('exact', 'Показывать точное количество'), ('status', 'Показывать статус (В наличии / Нет)'), ('detailed_status', 'Показывать детальный статус (В наличии / Мало / Нет)')], default='detailed_status', help_text='Как показывать наличие товара на сайте (действует только при отключенных общих настройках).', max_length=20, verbose_name='Стиль отображения остатков (индивидуальный)'),
        ),
    ]
