# Generated by Django 4.2.7 on 2025-09-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_use_default_stock_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'order', 'created_at'], 'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изображения товаров'},
        ),
    ]
